### ISSUE TITLE
Picture in Doctor Table not gender sensitive

### ISSUE THREAD

**Issue by pA1nD** [iHub-PTI/boldo-mobile#35]
Problem:
Female doctor shows a man placeholder.

Solution:
Show a female placeholder.

<img width="371" alt="Screenshot 2020-11-29 at 17 21 56" src="https://user-images.githubusercontent.com/8961100/100552684-6a37e380-3267-11eb-9441-597770420a90.png">

<img width="380" alt="Screenshot 2020-11-29 at 17 24 46" src="https://user-images.githubusercontent.com/8961100/100552745-cf8bd480-3267-11eb-814f-5fc0c5037653.png">

**Comment by pA1nD** [comment]
Sidenote: Gender was not included in the past. Now it is!

**Comment by zommerberg** [comment]
It is doctor sensitive!
