### ISSUE TITLE
Opening Doctors List triggers 3 times same requests

### ISSUE THREAD

**Issue by pA1nD** [iHub-PTI/boldo-mobile#41]
Problem:
Navigating to the doctors page triggers 3 times the same request (`/doctors?text=`).

It can be observed in the flutter dev tools and also in the server by adding a console.log into the endpoint.
![Screenshot 2020-11-30 at 17.51.33.png](https://images.zenhubusercontent.com/59a891da8f62dc7798c4d58a/59907c9f-d9c9-4158-bc91-dde31daa8cdc)

Expected Behaviour:
Opening the page should only trigger one request.

**Comment by zommerberg** [comment]
Does not happen to me, It is possible that this happens because the server returns 401 and then the client re-tries the request.
