### ISSUE TITLE
Improve the profile page form

### ISSUE THREAD

**Issue by zommerberg** [iHub-PTI/boldo-mobile#42]
# How our form works
Currently in the profile screen `profile_screen.dart` page we have a form. From this form we are able to navigate to `address_screen.dart`.
Inside the `address_screen.dart` we also have a form. It is actually extending the form we have from `profile_screen.dart`. Clicking on "submit" in any of the forms will trigger the same function `updateProfile`. This function takes the data from the provider (from both forms) and sends it to the server. We save the data from the inputs not onChange but onSubmit. So the data will go inside the provider when we try to submit the form. Then we get this data from provider and pass it to the server. We need a provider because we shared the data of the same form between 2 screens.

# Problem 1
Because of the functionality above if we try to remove some text from `profile_screen.dart` and then navigate to `address_screen.dart` we will successfully submit the form. This should not happen(or at least not as it happens right now). The changes we made in `profile_screen.dart` will not be reflected because we save the data onSave. We don't submit the form in `profile_screen.dart` so we don't save the new data. We submit the form in `address_screen.dart` so we save the data only there.

# Solution 1
Save the data onChange and not on onSave in the text controller.

# Problem 2
The errors are not shared between the forms. We should share them.

# Solution 2
Store the error inside the provider

**Comment by santiracca** [comment]
Interesting! I'll have a look at the form today and see if I can make a pull request!
